### ISSUE TITLE
无法签到，日志只出现时间

### ISSUE THREAD

**Issue by Tang1124** [jerrykuku/luci-app-jd-dailybonus#174]
全都配置好了。node也是自编译装上了。但是还是无法签到，签到只出现日期就没有继续了，怎么办啊。

**复现过程**
请描述如何复现错误r:
2021-06-03 15:06:41 Thursday
只出现这个就没了

**截图**
![屏幕截图 2021-06-03 151029](https://user-images.githubusercontent.com/62275546/120602758-e8c34700-c47d-11eb-8b89-39dea78a3a46.png)

**插件版本:**
 - Openwrt版本 OpenWrt 19.07.7
 - 主题以及版本 Luci-theme-Argon
 - 插件版本 V2.0.4

**桌面系统信息:**
 - 系统和版本 Win10 Ubuntu MacOS BigSur
 - 浏览器类型以及Chrome 
 - 版本

**手机系统信息:**
 - 设备类型：iPhone XsMax
 - 系统和版本 14.5
 - 浏览器类型 Chrome
 - 版本

**补充说明**
是不是还缺少什么依赖？

**Comment by jerrykuku** [comment]
应该还是node 的问题

**Comment by Tang1124** [comment]
> 应该还是node 的问题

我用的lede的源码编译的，换个其他的？

**Comment by Tang1124** [comment]
> 应该还是node 的问题

![屏幕截图 2021-06-04 085049](https://user-images.githubusercontent.com/62275546/120729549-07731d80-c512-11eb-8de5-8b091297ca72.png)
这是我目前的node版本

**Comment by Tang1124** [comment]
> 应该还是node 的问题
更新了一下获取不了二维码。rm -rf /tmp/luci-indexcache /tmp/luci-modulecache/*也执行了没用……
![屏幕截图 2021-06-04 093143](https://user-images.githubusercontent.com/62275546/120732334-b49c6480-c517-11eb-84ed-671f32805954.png)

**Comment by jerrykuku** [comment]
获取不到二维码 不是node的问题。 按F12 看下console.然后双机框 看看有没有什么错误

**Comment by zj53523094** [comment]
我也是，无法正常签到，全都配置好了。node也是自编译装上了。但签到就是只有时间没哟其他的了
![屏幕截图 2021-06-07 175215](https://user-images.githubusercontent.com/79318187/120996681-20512c80-c7b9-11eb-860a-b24cb65fcae8.png)
已安装的node版本
![屏幕截图 2021-06-07 175431](https://user-images.githubusercontent.com/79318187/120997063-7de57900-c7b9-11eb-9922-4307110d9b5f.png)

**Comment by zj53523094** [comment]
辛苦大佬指点一下![屏幕截图 2021-06-07 180424](https://user-images.githubusercontent.com/79318187/120998598-cfdace80-c7ba-11eb-8c58-b64ed295fde6.png)

**Comment by hue715** [comment]
用源码自行编译

> > 应该还是node 的问题
> > 更新了一下获取不了二维码。rm -rf /tmp/luci-indexcache /tmp/luci-modulecache/*也执行了没用……
> > ![屏幕截图 2021-06-04 093143](https://user-images.githubusercontent.com/62275546/120732334-b49c6480-c517-11eb-84ed-671f32805954.png)

你用的旧版本，最新版本在`账户cookie列表`下方，不会有`点击图标`字样，解决办法有：

1. 拉去代码，自行编译（不会编译的请自行谷歌）
2. 按照jerrykuku/luci-app-jd-dailybonus#165 ，手动修改cookie_tools.htm

**Comment by greedisgoood** [comment]
同样的情况，快两个月不能用了

**Comment by ma20at** [comment]
同样的问题，在5.10.46内核下安装成功，但是很多文件都缺少，/etc/config/jdxxx, /etc/init.d/jdxxx, /usr/lib/luca/luci下的jd文件也没有，我在5.4内核运行就正常，把5.4生的文件scp过去手工执行h会报错：
root@OpenWrt:/tmp# node /usr/share/jd-dailybonus/JD_DailyBonus.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /usr/share/jd-dailybonus/JD_DailyBonus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at /usr/share/jd-dailybonus/JD_DailyBonus.js:1790:23
    at nobyda (/usr/share/jd-dailybonus/JD_DailyBonus.js:1799:5)
    at Object.<anonymous> (/usr/share/jd-dailybonus/JD_DailyBonus.js:104:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/share/jd-dailybonus/JD_DailyBonus.js' ]
}

**Comment by ma20at** [comment]
lean的源码带了jd的插件有问题不完整编译安装后缺失了很多文件，要先去package/lean目录下把他的jd插件删除，再clone这个插件重新编译就没问题了，我昨晚对比了源码才发现。

**Comment by zj53523094** [comment]
万分感谢指点！

在 2021-07-06 11:07:12，ma20at ***@***.***> 写道：


lean的源码带了jd的插件有问题不完整编译安装后缺失了很多文件，要先去package/lean目录下把他的jd插件删除，再clone这个插件重新编译就没问题了，我昨晚对比了源码才发现。

**Comment by bhxjxxx** [comment]
> lean的源码带了jd的插件有问题不完整编译安装后缺失了很多文件，要先去package/lean目录下把他的jd插件删除，再clone这个插件重新编译就没问题了，我昨晚对比了源码才发现。

感谢，种种奇怪的问题clone了这个后全部迎刃而解了。
能解决不能检查脚本更新的问题。
