### ISSUE TITLE
更新后出现这样的问题了

### ISSUE THREAD

**Issue by zhaocz086** [jerrykuku/luci-app-jd-dailybonus#50]
2020-10-16 Friday
url.js:337
      this.hostname = toASCII(this.hostname, true);
Error: Cannot convert name to ASCII
    at Url.parse (url.js:337:23)
    at Object.urlParse [as parse] (url.js:97:13)
    at Request.init (/usr/lib/node/request/request.js:236:20)
    at new Request (/usr/lib/node/request/request.js:127:8)
    at request (/usr/lib/node/request/index.js:53:10)
    at Function.post (/usr/lib/node/request/index.js:61:12)
    at Object.post (/usr/share/jd-dailybonus/JD_DailyBonus.js:2442:20)
    at Timeout.setTimeout [as _onTimeout] (/usr/share/jd-dailybonus/JD_DailyBonus.js:322:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)

**Comment by jerrykuku** [comment]
更新需要卸载原来的node request。
